### ISSUE TITLE
intermittent panic+crash when BLE channel closes

### ISSUE THREAD

**Issue by esuomi** [niktheblak/ruuvitag-gollector#3]
Sup,

ruuvitag-gollector seems to crash every now and then if the BLE channel is closed for whatever reason. Here's what got grabbed into the logs:

```
panic: send on closed channel

goroutine 591104 [running]:
github.com/niktheblak/ruuvitag-gollector/pkg/scanner.(*Measurements).Channel.func1.1(0xd98f08, 0x209cb20)
        /home/pi/ruuvitag-gollector/pkg/scanner/meas.go:38 +0x1f0
github.com/go-ble/ble.Scan.func1(0xd98f08, 0x209cb20)
        /home/pi/go/pkg/mod/github.com/go-ble/ble@v0.0.0-20210519192345-b055c211937b/gatt.go:97 +0x60
created by github.com/go-ble/ble/linux/hci.(*HCI).handleLEAdvertisingReport
        /home/pi/go/pkg/mod/github.com/go-ble/ble@v0.0.0-20210519192345-b055c211937b/linux/hci/hci.go:435 +0x50
```

**Comment by niktheblak** [comment]
The go-ble is not a very actively maintained library but it does seem to have a new release made 5 months ago. I updated the dependencies of this project, let's see if this fixes the issue.

**Comment by esuomi** [comment]
Had another random crash just a few hours ago, so I'll update now and lets see if that makes things better :)

**Comment by esuomi** [comment]
@niktheblak  Well, sort of better but not quite, had another crash but now there's an ERROR instead of just panic:

```
ERROR Scan failed {"error": "received scan response 08:ef:3b:e3:08:39 with no associated Advertising Data packet"}
github.com/niktheblak/ruuvitag-gollector/pkg/scanner.(*Measurements).Channel.func1
        /home/pi/ruuvitag-gollector/pkg/scanner/meas.go:45
```

**Comment by esuomi** [comment]
And more:
```
ERROR Scan failed {"error": "Command Disallowed"}
github.com/niktheblak/ruuvitag-gollector/pkg/scanner.(*Measurements).Channel.func1
        /home/pi/ruuvitag-gollector/pkg/scanner/meas.go:45
panic: send on closed channel

goroutine 509028 [running]:
github.com/niktheblak/ruuvitag-gollector/pkg/scanner.(*Measurements).Channel.func1.1({0xf0544c, 0x3755428})
        /home/pi/ruuvitag-gollector/pkg/scanner/meas.go:38 +0x1fc
github.com/go-ble/ble.Scan.func1({0xf0544c, 0x3755428})
        /home/pi/go/pkg/mod/github.com/go-ble/ble@v0.0.0-20220207185428-60d1eecf2633/gatt.go:97 +0x5c
created by github.com/go-ble/ble/linux/hci.(*HCI).handleLEAdvertisingReport
        /home/pi/go/pkg/mod/github.com/go-ble/ble@v0.0.0-20220207185428-60d1eecf2633/linux/hci/hci.go:438 +0x4c
```

**Comment by niktheblak** [comment]
Hopefully this has resolved itself via ble library and Go compiler updates. I haven't had this crash in ages on RPI 3b and RPI 4.

**Comment by esuomi** [comment]
My Ruuvi ran out of battery and eventually I sold it to a colleague :) So I guess that counts as resolved.
